/**
 * 
 * DPT
 * 
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * 
 * Version: 1.0.0
 * 
 * Generated by OpenAPI Generator: https://openapi-generator.tech
 */

// package openapi3graphql-server

// default_api

export default {
    Query: {

    },

    Mutation: {

        // @return 
        SignUpPost: ($signUp) => {
            return {
                "signUp": ""
            };
        },

    }
}