/**
 * 
 * DPT
 * 
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * 
 * Version: 1.0.0
 * 
 * Generated by OpenAPI Generator: https://openapi-generator.tech
 */

// package openapi3graphql-server

// statments_api

export default {
    Query: {

        // @return Statment
        ListStatments: ($limit) => {
            return {
                "limit": "56"
            };
        },

        // @return Statment
        ShowStatmentById: ($statmentId) => {
            return {
                "statmentId": "statmentId_example"
            };
        },

    },

    Mutation: {

        // @return 
        CreateStatments: () => {
            return {
                
            };
        },

    }
}