/**
 * 
 * DPT
 * 
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * 
 * Version: 1.0.0
 * 
 * Generated by OpenAPI Generator: https://openapi-generator.tech
 */

// package openapi3graphql-server

// users_api

export default {
    Query: {

        // @return User
        ListUsers: ($limit) => {
            return {
                "limit": "56"
            };
        },

        // @return User
        ShowUserById: ($userId) => {
            return {
                "userId": "userId_example"
            };
        },

    },

    Mutation: {

        // @return 
        CreateUsers: () => {
            return {
                
            };
        },

    }
}